### ISSUE TITLE
Dotnet supported version

### ISSUE THREAD

**Issue by binaryphoenix** [michaelweber/Macrome#3]
Hi. Great work! Does it need a specific version of dotnet sdk installed? I installed the latest one for windows on a Windows 10 VM and built it without issues. When I run the DLL with the command "dotnet macrome.dll --build etc etc etc..." I get an error stating that the version 2.0 is not installed on the machine and it gives me the URL to download it. It's no longer supported but I guess I can finde it somewhere but the question is "do I really need it?".  Thanks!

**Comment by michaelweber** [comment]
Yeah - this one threw me for a loop too. I should probably upgrade the target version. 2.0 isn't available, but the 2.1 core runtime will work fine - https://dotnet.microsoft.com/download/dotnet-core/2.1. The naming is confusing since it seems like 3.0 is the latest...but while it can compile 2.x binaries fine...it can't run them some reason? Try it with this, and if that's no good I'll just update the build target to 3.x and it should work.

**Comment by binaryphoenix** [comment]
Thank you for your prompt response. Let me give it a try and I'll post the results.Thanks!

**Comment by binaryphoenix** [comment]
Hi. After installing the version "dotnet-sdk-2.1.806-win-x64" and rebooting I was able to generate the Excel file.

Command ran:
dotnet run build --decoy-document Docs\decoy_document.xls --payload Docs\popcalc.bin

Output:
Writing generated document to C:\Users\user\Desktop\Macrome-master\bin\Debug\netcoreapp2.0\output.xls

The generated Excel file works as expected popping up Calc.exe.  I'll try it with a different shellcode.  Thanks!

**Comment by michaelweber** [comment]
Fantastic! Glad this worked out! If you have any issues with various shellcode please let me know and I'll try to get it working! In the mean time I'm going to close this issue.

Cheers!
