### ISSUE TITLE
Auto_open Never Triggers

### ISSUE THREAD

**Issue by hlldz** [michaelweber/Macrome#8]
Hi,

Auto_open never triggers in Excel 2019 32 Bit (Language: Turkish) version.

I have tried it with both Macrome and the test macro below with International Macro Sheet. I am also sending the sample file attached.

=EXEC("notepad.exe")
=HALT()

[test-4.0.zip](https://github.com/michaelweber/Macrome/files/5465352/test-4.0.zip)

Do you have any advice?

**Comment by S3cur3Th1sSh1t** [comment]
Maybe the language is a problem? I just experienced that i have to translate every single Macro 4.0 command to get this technique working.

**Comment by michaelweber** [comment]
This is a good question - I'll need to take a look at this. That being said, when there were cyrillic characters being used, the auto_open function was triggering fine after making it international. "Worst" case we can always flag the field as an autoopen one instead of using the string approach, but that's more easily detectable. I've got some time to do some Macrome dev coming up and I'll take a look - apologies for the VERY delayed response here but it's been a busy end-of-year.

**Comment by hlldz** [comment]
Thank you for your interest. I am also following the problem and I plan to take the time to run different tests. I will share it if I get something worthwhile.

**Comment by hlldz** [comment]
Hi,

I have completed my tests. I think this problem is only valid for Turkish language Excel. I don't know if the Excel in another language is affected.

For example, here (https://twitter.com/Arno0x0x/status/1133338349710860288) @Arno0x has experienced a similar problem with the French language Excel and overcome the problem by using its French equivalent Auto_ouvrir instead of Auto_open.

In summary, the problem is not solved when only International Macro is selected. When International Macro is selected, it works when the commands in English are written into the cells and when it is run manually, but no action is triggered with Auto_open.

I tried the Turkish equivalent of Auto_open or possible equivalents, as Arno0x did but it didn't work. Microsoft does not have an official documentation on this subject. For this reason, if you wish, we can close the Issue?

**Comment by SneakyOttersec** [comment]
Hi everyone ,

Encoutered the same issue with Excel 2013 in French, indeed the International Macro only solve partially this issue. It seems like some ""keywords"" (i.e AutoOpen) are not interpreted even if it's in a International Macro.

However when replacing  "AutoOpen" in the Internaional Macro Sheet with the regional keyword (i.e : AutoOuvrir in French) this is working like a charm. -> Same with the Spanish language.

Maybe an option to choose if we want to use the default AutoOpen or not (--localized <keyword>) would be great ? 

Cheers !

**Comment by michaelweber** [comment]
One thing that malware authors have been doing for their side of things is going with the BuiltIn function but then having it reference a different label which is all null characters. This tends to break a lot of tooling and causes problems across the board - so maybe we can avoid this issue entirely since clearly the different regional versions of Office have localized their Auto_Open string comparisons.

**Comment by hlldz** [comment]
> One thing that malware authors have been doing for their side of things is going with the BuiltIn function but then having it reference a different label which is all null characters. This tends to break a lot of tooling and causes problems across the board - so maybe we can avoid this issue entirely since clearly the different regional versions of Office have localized their Auto_Open string comparisons.

Yes, you are right. There is neither a source nor a content about which languages the "Auto_open" value can be translated into and for which languages Office has support. Values for only German and French languages were found by simply translating the "Open" value. However, this is not valid for the Turkish language, it does not work. Therefore, we need to find an official source about which languages are supported (which I researched a lot, but could not find it) or a content should be added to README based on user comments.
